export * from './excel'
export * from './word'
export * from './area-de-transferencia'
export * from './armazenamento'
export * from './atualizacao-indices'
export * from './configuracoes-pessoais'
export * from './preenchimento-modelos'
